name: core
description: "deprx core"
version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  resource:
    path: ../resource
  api:
    path: ../api
  encryption:
    path: ../encryption
  common:
    path: ../common
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.2
  firebase_remote_config: ^5.1.2
  firebase_messaging: ^15.2.1
  sentry_flutter: ^8.10.1
  sentry_dio: ^8.10.1
  sentry_logging: ^8.10.1
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^5.3.1
  device_info_plus: ^11.1.0
  logger: ^2.5.0
  connectivity_plus: ^6.1.2
  google_sign_in: ^6.3.0
  flutter_local_notifications: ^17.2.3
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  package_info_plus: ^8.1.3
  get: ^4.7.2
  in_app_update: ^4.2.3
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  objectbox_generator: ^4.1.0

