name: common
description: "DepRx with Sham Melos"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  get: ^4.7.2
  youtube_player_iframe: ^5.2.0
  table_calendar: ^3.1.2
  extended_image: ^9.0.7
  fl_chart : ^0.69.2
  flutter_pdfview: ^1.3.4
  path_provider: ^2.1.5
  expandable_page_view: ^1.0.17
  resource:
    path: ../resource
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  build_runner: ^2.4.12
  objectbox_generator: ^4.0.3

flutter:
  uses-material-design: true