name: api
description: "deprx api"
version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  dio: ^5.6.0
  http: ^1.2.2
  core:
    path: ../core
  encryption:
    path: ../encryption
  sentry_flutter: ^8.10.1
  sentry_dio: ^8.10.1
  sentry_logging: ^8.10.1
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  build_runner: ^2.4.12

